
/*
 * 
 */

package org.example.sample;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.3
 * Wed Dec 26 00:22:19 IST 2012
 * Generated source version: 2.2.3
 * 
 */


@WebServiceClient(name = "sample", 
                  wsdlLocation = "file:src/main/resources/sample.wsdl",
                  targetNamespace = "http://www.example.org/sample/") 
public class Sample extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://www.example.org/sample/", "sample");
    public final static QName SampleSOAP = new QName("http://www.example.org/sample/", "sampleSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:src/main/resources/sample.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:src/main/resources/sample.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public Sample(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Sample(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Sample() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns Concatenation
     */
    @WebEndpoint(name = "sampleSOAP")
    public Concatenation getSampleSOAP() {
        return super.getPort(SampleSOAP, Concatenation.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Concatenation
     */
    @WebEndpoint(name = "sampleSOAP")
    public Concatenation getSampleSOAP(WebServiceFeature... features) {
        return super.getPort(SampleSOAP, Concatenation.class, features);
    }

}
