
package hari.home.cxf.runner;

import javax.xml.ws.Endpoint;

import org.example.sampleimpl.ConcatenationImpl;

/**
 * This class was generated by Apache CXF 2.2.3
 * Tue Dec 04 01:01:29 PST 2012
 * Generated source version: 2.2.3
 * 
 */
 
public class Concatenation_SampleSOAP_Server{

    protected Concatenation_SampleSOAP_Server() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new ConcatenationImpl();
        String address = "http://localhost:8085/cxf/services/sample";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception { 
        new Concatenation_SampleSOAP_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
