
package hari.home.cxf.runner;

import javax.xml.ws.Endpoint;
import org.example.sample.*;
/**
 * This class was generated by Apache CXF 2.2.3
 * Tue Dec 04 01:01:29 PST 2012
 * Generated source version: 2.2.3
 * 
 */
 
public class Concatenation_SampleSOAP_Server_Scala{

    protected Concatenation_SampleSOAP_Server_Scala() throws Exception {
        System.out.println("Starting Server");
        // in case of scala object, we can avoid the below line, by simply 
        // passing object name in Endpoint publish 
        Object implementor = new ConcatenationScalaImpl();
        String address = "http://localhost:8085/cxf/services/sample";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception { 
        new Concatenation_SampleSOAP_Server_Scala();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
